[package]
name = "tess2-sys"
version = "0.0.1"
authors = ["piaoger gong"]
edition = "2018"

[features]
default = []

# Whether or not to run bindgen
update-bindings = ["bindgen"]

[build-dependencies]
cc = "1.0"
bindgen = { version = "0.51", optional = true }
